version: '3.13'
services:
  pipeline:
    build: .
    restart: always
    container_name: pipeline_elt
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo